/*
* generated by Xtext
*/
package es.skyrim.alchemy.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import es.skyrim.alchemy.services.AlchemyLabGrammarAccess;

public class AlchemyLabParser extends AbstractContentAssistParser {
	
	@Inject
	private AlchemyLabGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected es.skyrim.alchemy.ui.contentassist.antlr.internal.InternalAlchemyLabParser createParser() {
		es.skyrim.alchemy.ui.contentassist.antlr.internal.InternalAlchemyLabParser result = new es.skyrim.alchemy.ui.contentassist.antlr.internal.InternalAlchemyLabParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEffectTypeAccess().getAlternatives(), "rule__EffectType__Alternatives");
					put(grammarAccess.getToxicityAccess().getAlternatives(), "rule__Toxicity__Alternatives");
					put(grammarAccess.getAlchemyLabModelAccess().getGroup(), "rule__AlchemyLabModel__Group__0");
					put(grammarAccess.getIngredientAccess().getGroup(), "rule__Ingredient__Group__0");
					put(grammarAccess.getIngredientAccess().getGroup_8(), "rule__Ingredient__Group_8__0");
					put(grammarAccess.getEffectAccess().getGroup(), "rule__Effect__Group__0");
					put(grammarAccess.getEffectAccess().getGroup_5(), "rule__Effect__Group_5__0");
					put(grammarAccess.getEffectRefAccess().getGroup(), "rule__EffectRef__Group__0");
					put(grammarAccess.getRecipeAccess().getGroup(), "rule__Recipe__Group__0");
					put(grammarAccess.getRecipeAccess().getGroup_9(), "rule__Recipe__Group_9__0");
					put(grammarAccess.getAlchemyLabModelAccess().getEffectsAssignment_0(), "rule__AlchemyLabModel__EffectsAssignment_0");
					put(grammarAccess.getAlchemyLabModelAccess().getIngredientsAssignment_1(), "rule__AlchemyLabModel__IngredientsAssignment_1");
					put(grammarAccess.getAlchemyLabModelAccess().getRecipesAssignment_2(), "rule__AlchemyLabModel__RecipesAssignment_2");
					put(grammarAccess.getIngredientAccess().getNameAssignment_1(), "rule__Ingredient__NameAssignment_1");
					put(grammarAccess.getIngredientAccess().getEffectsAssignment_3(), "rule__Ingredient__EffectsAssignment_3");
					put(grammarAccess.getIngredientAccess().getPriceAssignment_5(), "rule__Ingredient__PriceAssignment_5");
					put(grammarAccess.getIngredientAccess().getWeightAssignment_7(), "rule__Ingredient__WeightAssignment_7");
					put(grammarAccess.getIngredientAccess().getSourceAssignment_8_1(), "rule__Ingredient__SourceAssignment_8_1");
					put(grammarAccess.getEffectAccess().getNameAssignment_1(), "rule__Effect__NameAssignment_1");
					put(grammarAccess.getEffectAccess().getTypeAssignment_3(), "rule__Effect__TypeAssignment_3");
					put(grammarAccess.getEffectAccess().getDescriptionAssignment_5_1(), "rule__Effect__DescriptionAssignment_5_1");
					put(grammarAccess.getEffectRefAccess().getEffectAssignment_1(), "rule__EffectRef__EffectAssignment_1");
					put(grammarAccess.getRecipeAccess().getToxicityAssignment_0(), "rule__Recipe__ToxicityAssignment_0");
					put(grammarAccess.getRecipeAccess().getNameAssignment_1(), "rule__Recipe__NameAssignment_1");
					put(grammarAccess.getRecipeAccess().getEffectsAssignment_3(), "rule__Recipe__EffectsAssignment_3");
					put(grammarAccess.getRecipeAccess().getPriceAssignment_5(), "rule__Recipe__PriceAssignment_5");
					put(grammarAccess.getRecipeAccess().getIngredientsAssignment_8(), "rule__Recipe__IngredientsAssignment_8");
					put(grammarAccess.getRecipeAccess().getIngredientsAssignment_9_1(), "rule__Recipe__IngredientsAssignment_9_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			es.skyrim.alchemy.ui.contentassist.antlr.internal.InternalAlchemyLabParser typedParser = (es.skyrim.alchemy.ui.contentassist.antlr.internal.InternalAlchemyLabParser) parser;
			typedParser.entryRuleAlchemyLabModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AlchemyLabGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AlchemyLabGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
