/*
* generated by Xtext
*/
package es.skyrim.alchemy.ui.contentassist;

import es.skyrim.alchemy.ui.contentassist.AbstractAlchemyLabProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AlchemyLabProposalProvider extends AbstractAlchemyLabProposalProvider {

}
