/*
* generated by Xtext
*/
package es.skyrim.alchemy;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AlchemyLabUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return es.skyrim.alchemy.ui.internal.AlchemyLabActivator.getInstance().getInjector("es.skyrim.alchemy.AlchemyLab");
	}
	
}
