package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Alchemy_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("c983b263-4a3e-46fb-be9c-dc95b4d6bba6(es.skyrim.alchemy)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
