package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EffectReference extends BaseConcept {
  public static final String concept = "es.skyrim.alchemy.structure.EffectReference";
  public static final String EFFECT = "effect";

  public EffectReference(SNode node) {
    super(node);
  }

  public IEffect getEffect() {
    return (IEffect) this.getReferent(IEffect.class, EffectReference.EFFECT);
  }

  public void setEffect(IEffect node) {
    super.setReferent(EffectReference.EFFECT, node);
  }

  public static EffectReference newInstance(SModel sm, boolean init) {
    return (EffectReference) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.EffectReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EffectReference newInstance(SModel sm) {
    return EffectReference.newInstance(sm, false);
  }
}
