package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Effect extends BaseConcept implements IEffect {
  public static final String concept = "es.skyrim.alchemy.structure.Effect";
  public static final String DESCRIPTION = "description";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String NATURE = "nature";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Effect(SNode node) {
    super(node);
  }

  public String getDescription() {
    return this.getProperty(Effect.DESCRIPTION);
  }

  public void setDescription(String value) {
    this.setProperty(Effect.DESCRIPTION, value);
  }

  public String getName() {
    return this.getProperty(Effect.NAME);
  }

  public void setName(String value) {
    this.setProperty(Effect.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Effect.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Effect.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Effect.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Effect.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Effect.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Effect.VIRTUAL_PACKAGE, value);
  }

  public EffectNature getNature() {
    String value = super.getProperty(Effect.NATURE);
    return EffectNature.parseValue(value);
  }

  public void setNature(EffectNature value) {
    super.setProperty(Effect.NATURE, value.getValueAsString());
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Effect.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Effect.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Effect.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Effect.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Effect.SMODEL_ATTRIBUTE, node);
  }

  public static Effect newInstance(SModel sm, boolean init) {
    return (Effect) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.Effect", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Effect newInstance(SModel sm) {
    return Effect.newInstance(sm, false);
  }
}
