package es.skyrim.alchemy.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum EffectNature {
  FORTIFY("FORTIFY", "F"),
  WEAKEN("WEAKEN", "W");

  private String myName;
  private String myValue;

  EffectNature(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

  public static List<EffectNature> getConstants() {
    List<EffectNature> list = ListSequence.fromList(new LinkedList<EffectNature>());
    ListSequence.fromList(list).addElement(EffectNature.FORTIFY);
    ListSequence.fromList(list).addElement(EffectNature.WEAKEN);
    return list;
  }

  public static EffectNature getDefault() {
    return EffectNature.FORTIFY;
  }

  public static EffectNature parseValue(String value) {
    if (value == null) {
      return EffectNature.getDefault();
    }
    if (value.equals(EffectNature.FORTIFY.getValueAsString())) {
      return EffectNature.FORTIFY;
    }
    if (value.equals(EffectNature.WEAKEN.getValueAsString())) {
      return EffectNature.WEAKEN;
    }
    return EffectNature.getDefault();
  }
}
