package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.IContainer;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EffectTome extends BaseConcept implements IContainer, INamedConcept {
  public static final String concept = "es.skyrim.alchemy.structure.EffectTome";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String NAME = "name";
  public static final String EFFECT = "effect";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public EffectTome(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(EffectTome.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(EffectTome.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(EffectTome.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(EffectTome.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(EffectTome.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(EffectTome.VIRTUAL_PACKAGE, value);
  }

  public String getName() {
    return this.getProperty(EffectTome.NAME);
  }

  public void setName(String value) {
    this.setProperty(EffectTome.NAME, value);
  }

  public int getEffectsCount() {
    return this.getChildCount(EffectTome.EFFECT);
  }

  public Iterator<IEffect> effects() {
    return this.children(IEffect.class, EffectTome.EFFECT);
  }

  public List<IEffect> getEffects() {
    return this.getChildren(IEffect.class, EffectTome.EFFECT);
  }

  public void addEffect(IEffect node) {
    this.addChild(EffectTome.EFFECT, node);
  }

  public void insertEffect(IEffect prev, IEffect node) {
    this.insertChild(prev, EffectTome.EFFECT, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(EffectTome.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, EffectTome.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, EffectTome.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(EffectTome.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, EffectTome.SMODEL_ATTRIBUTE, node);
  }

  public static EffectTome newInstance(SModel sm, boolean init) {
    return (EffectTome) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.EffectTome", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EffectTome newInstance(SModel sm) {
    return EffectTome.newInstance(sm, false);
  }
}
