package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EffectAlias extends BaseConcept implements IEffect {
  public static final String concept = "es.skyrim.alchemy.structure.EffectAlias";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String EFFECT = "effect";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public EffectAlias(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(EffectAlias.NAME);
  }

  public void setName(String value) {
    this.setProperty(EffectAlias.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(EffectAlias.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(EffectAlias.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(EffectAlias.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(EffectAlias.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(EffectAlias.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(EffectAlias.VIRTUAL_PACKAGE, value);
  }

  public Effect getEffect() {
    return (Effect) this.getReferent(Effect.class, EffectAlias.EFFECT);
  }

  public void setEffect(Effect node) {
    super.setReferent(EffectAlias.EFFECT, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(EffectAlias.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, EffectAlias.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, EffectAlias.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(EffectAlias.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, EffectAlias.SMODEL_ATTRIBUTE, node);
  }

  public static EffectAlias newInstance(SModel sm, boolean init) {
    return (EffectAlias) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.EffectAlias", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EffectAlias newInstance(SModel sm) {
    return EffectAlias.newInstance(sm, false);
  }
}
