package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;

public interface IEffect extends INamedConcept {
  public static final String concept = "es.skyrim.alchemy.structure.IEffect";
}
