package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IngredientReference extends BaseConcept {
  public static final String concept = "es.skyrim.alchemy.structure.IngredientReference";
  public static final String INGREDIENT = "ingredient";

  public IngredientReference(SNode node) {
    super(node);
  }

  public Ingredient getIngredient() {
    return (Ingredient) this.getReferent(Ingredient.class, IngredientReference.INGREDIENT);
  }

  public void setIngredient(Ingredient node) {
    super.setReferent(IngredientReference.INGREDIENT, node);
  }

  public static IngredientReference newInstance(SModel sm, boolean init) {
    return (IngredientReference) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.IngredientReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IngredientReference newInstance(SModel sm) {
    return IngredientReference.newInstance(sm, false);
  }
}
