package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IngredientAlias extends BaseConcept implements IIngredient {
  public static final String concept = "es.skyrim.alchemy.structure.IngredientAlias";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String INGREDIENT = "ingredient";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public IngredientAlias(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(IngredientAlias.NAME);
  }

  public void setName(String value) {
    this.setProperty(IngredientAlias.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(IngredientAlias.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(IngredientAlias.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(IngredientAlias.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(IngredientAlias.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(IngredientAlias.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(IngredientAlias.VIRTUAL_PACKAGE, value);
  }

  public Ingredient getIngredient() {
    return (Ingredient) this.getChild(Ingredient.class, IngredientAlias.INGREDIENT);
  }

  public void setIngredient(Ingredient node) {
    super.setChild(IngredientAlias.INGREDIENT, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(IngredientAlias.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, IngredientAlias.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, IngredientAlias.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(IngredientAlias.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, IngredientAlias.SMODEL_ATTRIBUTE, node);
  }

  public static IngredientAlias newInstance(SModel sm, boolean init) {
    return (IngredientAlias) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.IngredientAlias", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IngredientAlias newInstance(SModel sm) {
    return IngredientAlias.newInstance(sm, false);
  }
}
