package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.IContainer;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MixtureList extends BaseConcept implements IContainer, INamedConcept {
  public static final String concept = "es.skyrim.alchemy.structure.MixtureList";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String NAME = "name";
  public static final String MIXTURE = "mixture";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public MixtureList(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(MixtureList.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(MixtureList.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(MixtureList.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(MixtureList.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(MixtureList.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(MixtureList.VIRTUAL_PACKAGE, value);
  }

  public String getName() {
    return this.getProperty(MixtureList.NAME);
  }

  public void setName(String value) {
    this.setProperty(MixtureList.NAME, value);
  }

  public int getMixturesCount() {
    return this.getChildCount(MixtureList.MIXTURE);
  }

  public Iterator<Mixture> mixtures() {
    return this.children(Mixture.class, MixtureList.MIXTURE);
  }

  public List<Mixture> getMixtures() {
    return this.getChildren(Mixture.class, MixtureList.MIXTURE);
  }

  public void addMixture(Mixture node) {
    this.addChild(MixtureList.MIXTURE, node);
  }

  public void insertMixture(Mixture prev, Mixture node) {
    this.insertChild(prev, MixtureList.MIXTURE, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(MixtureList.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, MixtureList.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, MixtureList.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(MixtureList.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, MixtureList.SMODEL_ATTRIBUTE, node);
  }

  public static MixtureList newInstance(SModel sm, boolean init) {
    return (MixtureList) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.MixtureList", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MixtureList newInstance(SModel sm) {
    return MixtureList.newInstance(sm, false);
  }
}
