package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Mixture extends BaseConcept implements INamedConcept {
  public static final String concept = "es.skyrim.alchemy.structure.Mixture";
  public static final String PRICE = "price";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String RECIPE = "recipe";
  public static final String EFFECT = "effect";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Mixture(SNode node) {
    super(node);
  }

  public String getPrice() {
    return this.getProperty(Mixture.PRICE);
  }

  public void setPrice(String value) {
    this.setProperty(Mixture.PRICE, value);
  }

  public String getName() {
    return this.getProperty(Mixture.NAME);
  }

  public void setName(String value) {
    this.setProperty(Mixture.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Mixture.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Mixture.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Mixture.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Mixture.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Mixture.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Mixture.VIRTUAL_PACKAGE, value);
  }

  public Recipe getRecipe() {
    return (Recipe) this.getChild(Recipe.class, Mixture.RECIPE);
  }

  public void setRecipe(Recipe node) {
    super.setChild(Mixture.RECIPE, node);
  }

  public int getEffectsCount() {
    return this.getChildCount(Mixture.EFFECT);
  }

  public Iterator<EffectReference> effects() {
    return this.children(EffectReference.class, Mixture.EFFECT);
  }

  public List<EffectReference> getEffects() {
    return this.getChildren(EffectReference.class, Mixture.EFFECT);
  }

  public void addEffect(EffectReference node) {
    this.addChild(Mixture.EFFECT, node);
  }

  public void insertEffect(EffectReference prev, EffectReference node) {
    this.insertChild(prev, Mixture.EFFECT, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Mixture.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Mixture.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Mixture.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Mixture.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Mixture.SMODEL_ATTRIBUTE, node);
  }

  public static Mixture newInstance(SModel sm, boolean init) {
    return (Mixture) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.Mixture", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Mixture newInstance(SModel sm) {
    return Mixture.newInstance(sm, false);
  }
}
