package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;

public class number_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    String testValue = null;
    if (value == null) {
      testValue = "";
    } else {
      testValue = value;
    }
    return testValue.matches("[0-9]+(\\.[0-9]+)?");
  }
}
