package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Poison extends Mixture {
  public static final String concept = "es.skyrim.alchemy.structure.Poison";

  public Poison(SNode node) {
    super(node);
  }

  public static Poison newInstance(SModel sm, boolean init) {
    return (Poison) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.Poison", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Poison newInstance(SModel sm) {
    return Poison.newInstance(sm, false);
  }
}
