package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Potion extends Mixture {
  public static final String concept = "es.skyrim.alchemy.structure.Potion";

  public Potion(SNode node) {
    super(node);
  }

  public static Potion newInstance(SModel sm, boolean init) {
    return (Potion) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.Potion", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Potion newInstance(SModel sm) {
    return Potion.newInstance(sm, false);
  }
}
