package es.skyrim.alchemy.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.IContainer;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Satchel extends BaseConcept implements IContainer, INamedConcept {
  public static final String concept = "es.skyrim.alchemy.structure.Satchel";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String NAME = "name";
  public static final String INGREDIENT = "ingredient";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Satchel(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(Satchel.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Satchel.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Satchel.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Satchel.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Satchel.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Satchel.VIRTUAL_PACKAGE, value);
  }

  public String getName() {
    return this.getProperty(Satchel.NAME);
  }

  public void setName(String value) {
    this.setProperty(Satchel.NAME, value);
  }

  public int getIngredientsCount() {
    return this.getChildCount(Satchel.INGREDIENT);
  }

  public Iterator<IIngredient> ingredients() {
    return this.children(IIngredient.class, Satchel.INGREDIENT);
  }

  public List<IIngredient> getIngredients() {
    return this.getChildren(IIngredient.class, Satchel.INGREDIENT);
  }

  public void addIngredient(IIngredient node) {
    this.addChild(Satchel.INGREDIENT, node);
  }

  public void insertIngredient(IIngredient prev, IIngredient node) {
    this.insertChild(prev, Satchel.INGREDIENT, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Satchel.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Satchel.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Satchel.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Satchel.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Satchel.SMODEL_ATTRIBUTE, node);
  }

  public static Satchel newInstance(SModel sm, boolean init) {
    return (Satchel) SModelUtil_new.instantiateConceptDeclaration("es.skyrim.alchemy.structure.Satchel", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Satchel newInstance(SModel sm) {
    return Satchel.newInstance(sm, false);
  }
}
