<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="alchemyLab"
    nsURI="http://www.skyrim.es/alchemy/AlchemyLab" nsPrefix="alchemyLab">
  <eClassifiers xsi:type="ecore:EClass" name="AlchemyLabModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="effects" upperBound="-1"
        eType="#//Effect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ingredients" upperBound="-1"
        eType="#//Ingredient" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipes" upperBound="-1"
        eType="#//Recipe" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Effect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="effect" eType="#//Effect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EffectDef" eSuperTypes="#//Effect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EffectType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EffectType">
    <eLiterals name="FORTIFY" literal="+"/>
    <eLiterals name="WEAKEN" value="1" literal="-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EffectAlias" eSuperTypes="#//Effect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ingredient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ingredient" eType="#//Ingredient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IngredientDef" eSuperTypes="#//Ingredient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effects" upperBound="-1"
        eType="#//Effect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IngredientAlias" eSuperTypes="#//Ingredient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Recipe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toxicity" eType="#//Toxicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effects" upperBound="-1"
        eType="#//Effect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ingredients" upperBound="-1"
        eType="#//Ingredient" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Toxicity">
    <eLiterals name="POTION" literal="potion"/>
    <eLiterals name="POISON" value="1" literal="poison"/>
    <eLiterals name="MIXTURE" value="2" literal="mixture"/>
  </eClassifiers>
</ecore:EPackage>
