/*
 * generated by Xtext
 */
package es.skyrim.alchemy.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AlchemyLabUiModule extends es.skyrim.alchemy.ui.AbstractAlchemyLabUiModule {
	public AlchemyLabUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
