/*
* generated by Xtext
*/

package es.skyrim.alchemy.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class AlchemyLabGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class AlchemyLabModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AlchemyLabModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEffectsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cEffectsEffectParserRuleCall_0_0 = (RuleCall)cEffectsAssignment_0.eContents().get(0);
		private final Assignment cIngredientsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIngredientsIngredientParserRuleCall_1_0 = (RuleCall)cIngredientsAssignment_1.eContents().get(0);
		private final Assignment cRecipesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRecipesRecipeParserRuleCall_2_0 = (RuleCall)cRecipesAssignment_2.eContents().get(0);
		
		//AlchemyLabModel:
		//	effects+=Effect* ingredients+=Ingredient* recipes+=Recipe*;
		public ParserRule getRule() { return rule; }

		//effects+=Effect* ingredients+=Ingredient* recipes+=Recipe*
		public Group getGroup() { return cGroup; }

		//effects+=Effect*
		public Assignment getEffectsAssignment_0() { return cEffectsAssignment_0; }

		//Effect
		public RuleCall getEffectsEffectParserRuleCall_0_0() { return cEffectsEffectParserRuleCall_0_0; }

		//ingredients+=Ingredient*
		public Assignment getIngredientsAssignment_1() { return cIngredientsAssignment_1; }

		//Ingredient
		public RuleCall getIngredientsIngredientParserRuleCall_1_0() { return cIngredientsIngredientParserRuleCall_1_0; }

		//recipes+=Recipe*
		public Assignment getRecipesAssignment_2() { return cRecipesAssignment_2; }

		//Recipe
		public RuleCall getRecipesRecipeParserRuleCall_2_0() { return cRecipesRecipeParserRuleCall_2_0; }
	}

	public class IngredientElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Ingredient");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIngredientKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEffectsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEffectsEffectRefParserRuleCall_3_0 = (RuleCall)cEffectsAssignment_3.eContents().get(0);
		private final Keyword cPriceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPriceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPriceNUMBERTerminalRuleCall_5_0 = (RuleCall)cPriceAssignment_5.eContents().get(0);
		private final Keyword cWeightKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cWeightAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cWeightNUMBERTerminalRuleCall_7_0 = (RuleCall)cWeightAssignment_7.eContents().get(0);
		private final Keyword cSourceKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cSourceAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cSourceSTRINGTerminalRuleCall_9_0 = (RuleCall)cSourceAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Ingredient:
		//	"ingredient" name=ID "{" effects+=EffectRef* "price:" price=NUMBER "weight:" weight=NUMBER "source:" source=STRING
		//	"}";
		public ParserRule getRule() { return rule; }

		//"ingredient" name=ID "{" effects+=EffectRef* "price:" price=NUMBER "weight:" weight=NUMBER "source:" source=STRING "}"
		public Group getGroup() { return cGroup; }

		//"ingredient"
		public Keyword getIngredientKeyword_0() { return cIngredientKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//effects+=EffectRef*
		public Assignment getEffectsAssignment_3() { return cEffectsAssignment_3; }

		//EffectRef
		public RuleCall getEffectsEffectRefParserRuleCall_3_0() { return cEffectsEffectRefParserRuleCall_3_0; }

		//"price:"
		public Keyword getPriceKeyword_4() { return cPriceKeyword_4; }

		//price=NUMBER
		public Assignment getPriceAssignment_5() { return cPriceAssignment_5; }

		//NUMBER
		public RuleCall getPriceNUMBERTerminalRuleCall_5_0() { return cPriceNUMBERTerminalRuleCall_5_0; }

		//"weight:"
		public Keyword getWeightKeyword_6() { return cWeightKeyword_6; }

		//weight=NUMBER
		public Assignment getWeightAssignment_7() { return cWeightAssignment_7; }

		//NUMBER
		public RuleCall getWeightNUMBERTerminalRuleCall_7_0() { return cWeightNUMBERTerminalRuleCall_7_0; }

		//"source:"
		public Keyword getSourceKeyword_8() { return cSourceKeyword_8; }

		//source=STRING
		public Assignment getSourceAssignment_9() { return cSourceAssignment_9; }

		//STRING
		public RuleCall getSourceSTRINGTerminalRuleCall_9_0() { return cSourceSTRINGTerminalRuleCall_9_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class EffectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Effect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeEffectTypeEnumRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		
		//Effect:
		//	"effect" name=ID "(" type=EffectType ")" (":" description=STRING)?;
		public ParserRule getRule() { return rule; }

		//"effect" name=ID "(" type=EffectType ")" (":" description=STRING)?
		public Group getGroup() { return cGroup; }

		//"effect"
		public Keyword getEffectKeyword_0() { return cEffectKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//type=EffectType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }

		//EffectType
		public RuleCall getTypeEffectTypeEnumRuleCall_3_0() { return cTypeEffectTypeEnumRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }

		//(":" description=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//":"
		public Keyword getColonKeyword_5_0() { return cColonKeyword_5_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_5_1_0() { return cDescriptionSTRINGTerminalRuleCall_5_1_0; }
	}

	public class EffectRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EffectRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEffectAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cEffectEffectCrossReference_1_0 = (CrossReference)cEffectAssignment_1.eContents().get(0);
		private final RuleCall cEffectEffectIDTerminalRuleCall_1_0_1 = (RuleCall)cEffectEffectCrossReference_1_0.eContents().get(1);
		
		//EffectRef returns Effect:
		//	"->" effect=[Effect];
		public ParserRule getRule() { return rule; }

		//"->" effect=[Effect]
		public Group getGroup() { return cGroup; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_0() { return cHyphenMinusGreaterThanSignKeyword_0; }

		//effect=[Effect]
		public Assignment getEffectAssignment_1() { return cEffectAssignment_1; }

		//[Effect]
		public CrossReference getEffectEffectCrossReference_1_0() { return cEffectEffectCrossReference_1_0; }

		//ID
		public RuleCall getEffectEffectIDTerminalRuleCall_1_0_1() { return cEffectEffectIDTerminalRuleCall_1_0_1; }
	}

	public class RecipeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Recipe");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cToxicityAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cToxicityToxicityEnumRuleCall_0_0 = (RuleCall)cToxicityAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEffectsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEffectsEffectRefParserRuleCall_3_0 = (RuleCall)cEffectsAssignment_3.eContents().get(0);
		private final Keyword cPriceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPriceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPriceNUMBERTerminalRuleCall_5_0 = (RuleCall)cPriceAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cEqualsSignKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cIngredientsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cIngredientsIngredientCrossReference_8_0 = (CrossReference)cIngredientsAssignment_8.eContents().get(0);
		private final RuleCall cIngredientsIngredientIDTerminalRuleCall_8_0_1 = (RuleCall)cIngredientsIngredientCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cPlusSignKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cIngredientsAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cIngredientsIngredientCrossReference_9_1_0 = (CrossReference)cIngredientsAssignment_9_1.eContents().get(0);
		private final RuleCall cIngredientsIngredientIDTerminalRuleCall_9_1_0_1 = (RuleCall)cIngredientsIngredientCrossReference_9_1_0.eContents().get(1);
		
		//Recipe:
		//	toxicity=Toxicity name=ID "{" effects+=EffectRef+ "price:" price=NUMBER "}" "=" ingredients+=[Ingredient] ("+"
		//	ingredients+=[Ingredient])*;
		public ParserRule getRule() { return rule; }

		//toxicity=Toxicity name=ID "{" effects+=EffectRef+ "price:" price=NUMBER "}" "=" ingredients+=[Ingredient] ("+"
		//ingredients+=[Ingredient])*
		public Group getGroup() { return cGroup; }

		//toxicity=Toxicity
		public Assignment getToxicityAssignment_0() { return cToxicityAssignment_0; }

		//Toxicity
		public RuleCall getToxicityToxicityEnumRuleCall_0_0() { return cToxicityToxicityEnumRuleCall_0_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//effects+=EffectRef+
		public Assignment getEffectsAssignment_3() { return cEffectsAssignment_3; }

		//EffectRef
		public RuleCall getEffectsEffectRefParserRuleCall_3_0() { return cEffectsEffectRefParserRuleCall_3_0; }

		//"price:"
		public Keyword getPriceKeyword_4() { return cPriceKeyword_4; }

		//price=NUMBER
		public Assignment getPriceAssignment_5() { return cPriceAssignment_5; }

		//NUMBER
		public RuleCall getPriceNUMBERTerminalRuleCall_5_0() { return cPriceNUMBERTerminalRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }

		//"="
		public Keyword getEqualsSignKeyword_7() { return cEqualsSignKeyword_7; }

		//ingredients+=[Ingredient]
		public Assignment getIngredientsAssignment_8() { return cIngredientsAssignment_8; }

		//[Ingredient]
		public CrossReference getIngredientsIngredientCrossReference_8_0() { return cIngredientsIngredientCrossReference_8_0; }

		//ID
		public RuleCall getIngredientsIngredientIDTerminalRuleCall_8_0_1() { return cIngredientsIngredientIDTerminalRuleCall_8_0_1; }

		//("+" ingredients+=[Ingredient])*
		public Group getGroup_9() { return cGroup_9; }

		//"+"
		public Keyword getPlusSignKeyword_9_0() { return cPlusSignKeyword_9_0; }

		//ingredients+=[Ingredient]
		public Assignment getIngredientsAssignment_9_1() { return cIngredientsAssignment_9_1; }

		//[Ingredient]
		public CrossReference getIngredientsIngredientCrossReference_9_1_0() { return cIngredientsIngredientCrossReference_9_1_0; }

		//ID
		public RuleCall getIngredientsIngredientIDTerminalRuleCall_9_1_0_1() { return cIngredientsIngredientIDTerminalRuleCall_9_1_0_1; }
	}
	
	
	public class EffectTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "EffectType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFORTIFYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFORTIFYPlusSignKeyword_0_0 = (Keyword)cFORTIFYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cWEAKENEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cWEAKENHyphenMinusKeyword_1_0 = (Keyword)cWEAKENEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum EffectType:
		//	FORTIFY="+" | WEAKEN="-";
		public EnumRule getRule() { return rule; }

		//FORTIFY="+" | WEAKEN="-"
		public Alternatives getAlternatives() { return cAlternatives; }

		//FORTIFY="+"
		public EnumLiteralDeclaration getFORTIFYEnumLiteralDeclaration_0() { return cFORTIFYEnumLiteralDeclaration_0; }

		//"+"
		public Keyword getFORTIFYPlusSignKeyword_0_0() { return cFORTIFYPlusSignKeyword_0_0; }

		//WEAKEN="-"
		public EnumLiteralDeclaration getWEAKENEnumLiteralDeclaration_1() { return cWEAKENEnumLiteralDeclaration_1; }

		//"-"
		public Keyword getWEAKENHyphenMinusKeyword_1_0() { return cWEAKENHyphenMinusKeyword_1_0; }
	}

	public class ToxicityElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Toxicity");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPOTIONEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPOTIONPotionKeyword_0_0 = (Keyword)cPOTIONEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPOISONEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPOISONPoisonKeyword_1_0 = (Keyword)cPOISONEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Toxicity:
		//	POTION="potion" | POISON="poison";
		public EnumRule getRule() { return rule; }

		//POTION="potion" | POISON="poison"
		public Alternatives getAlternatives() { return cAlternatives; }

		//POTION="potion"
		public EnumLiteralDeclaration getPOTIONEnumLiteralDeclaration_0() { return cPOTIONEnumLiteralDeclaration_0; }

		//"potion"
		public Keyword getPOTIONPotionKeyword_0_0() { return cPOTIONPotionKeyword_0_0; }

		//POISON="poison"
		public EnumLiteralDeclaration getPOISONEnumLiteralDeclaration_1() { return cPOISONEnumLiteralDeclaration_1; }

		//"poison"
		public Keyword getPOISONPoisonKeyword_1_0() { return cPOISONPoisonKeyword_1_0; }
	}
	
	private AlchemyLabModelElements pAlchemyLabModel;
	private IngredientElements pIngredient;
	private EffectElements pEffect;
	private EffectTypeElements unknownRuleEffectType;
	private EffectRefElements pEffectRef;
	private RecipeElements pRecipe;
	private ToxicityElements unknownRuleToxicity;
	private TerminalRule tID;
	private TerminalRule tSTRING;
	private TerminalRule tNUMBER;
	private TerminalRule tINT;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public AlchemyLabGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//AlchemyLabModel:
	//	effects+=Effect* ingredients+=Ingredient* recipes+=Recipe*;
	public AlchemyLabModelElements getAlchemyLabModelAccess() {
		return (pAlchemyLabModel != null) ? pAlchemyLabModel : (pAlchemyLabModel = new AlchemyLabModelElements());
	}
	
	public ParserRule getAlchemyLabModelRule() {
		return getAlchemyLabModelAccess().getRule();
	}

	//Ingredient:
	//	"ingredient" name=ID "{" effects+=EffectRef* "price:" price=NUMBER "weight:" weight=NUMBER "source:" source=STRING
	//	"}";
	public IngredientElements getIngredientAccess() {
		return (pIngredient != null) ? pIngredient : (pIngredient = new IngredientElements());
	}
	
	public ParserRule getIngredientRule() {
		return getIngredientAccess().getRule();
	}

	//Effect:
	//	"effect" name=ID "(" type=EffectType ")" (":" description=STRING)?;
	public EffectElements getEffectAccess() {
		return (pEffect != null) ? pEffect : (pEffect = new EffectElements());
	}
	
	public ParserRule getEffectRule() {
		return getEffectAccess().getRule();
	}

	//enum EffectType:
	//	FORTIFY="+" | WEAKEN="-";
	public EffectTypeElements getEffectTypeAccess() {
		return (unknownRuleEffectType != null) ? unknownRuleEffectType : (unknownRuleEffectType = new EffectTypeElements());
	}
	
	public EnumRule getEffectTypeRule() {
		return getEffectTypeAccess().getRule();
	}

	//EffectRef returns Effect:
	//	"->" effect=[Effect];
	public EffectRefElements getEffectRefAccess() {
		return (pEffectRef != null) ? pEffectRef : (pEffectRef = new EffectRefElements());
	}
	
	public ParserRule getEffectRefRule() {
		return getEffectRefAccess().getRule();
	}

	//Recipe:
	//	toxicity=Toxicity name=ID "{" effects+=EffectRef+ "price:" price=NUMBER "}" "=" ingredients+=[Ingredient] ("+"
	//	ingredients+=[Ingredient])*;
	public RecipeElements getRecipeAccess() {
		return (pRecipe != null) ? pRecipe : (pRecipe = new RecipeElements());
	}
	
	public ParserRule getRecipeRule() {
		return getRecipeAccess().getRule();
	}

	//enum Toxicity:
	//	POTION="potion" | POISON="poison";
	public ToxicityElements getToxicityAccess() {
		return (unknownRuleToxicity != null) ? unknownRuleToxicity : (unknownRuleToxicity = new ToxicityElements());
	}
	
	public EnumRule getToxicityRule() {
		return getToxicityAccess().getRule();
	}

	//terminal ID:
	//	"\"" "^"? ("a".."z" | "A".."Z" | " " | "ä" | "Ä" | "ö" | "Ö" | "Ü" | "ü")+ "\"";
	public TerminalRule getIDRule() {
		return (tID != null) ? tID : (tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ID"));
	} 

	//terminal STRING:
	//	"\'" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return (tSTRING != null) ? tSTRING : (tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "STRING"));
	} 

	//terminal NUMBER returns ecore::EFloat:
	//	"0".."9"+ ("." "0".."9"+)?;
	public TerminalRule getNUMBERRule() {
		return (tNUMBER != null) ? tNUMBER : (tNUMBER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NUMBER"));
	} 

	//terminal INT returns ecore::EInt:
	//	"this one has been deactivated";
	public TerminalRule getINTRule() {
		return (tINT != null) ? tINT : (tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "INT"));
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
