/*
* generated by Xtext
*/
package es.skyrim.alchemy.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import es.skyrim.alchemy.services.AlchemyLabGrammarAccess;

public class AlchemyLabParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AlchemyLabGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected es.skyrim.alchemy.parser.antlr.internal.InternalAlchemyLabParser createParser(XtextTokenStream stream) {
		return new es.skyrim.alchemy.parser.antlr.internal.InternalAlchemyLabParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AlchemyLabModel";
	}
	
	public AlchemyLabGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AlchemyLabGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
