/*
* generated by Xtext
*/
package es.skyrim.alchemy.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AlchemyLabAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("es/skyrim/alchemy/parser/antlr/internal/InternalAlchemyLab.tokens");
	}
}
