package es.skyrim.alchemy.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"es.skyrim.alchemy.structure.AlchemyLab", "es.skyrim.alchemy.structure.Effect", "es.skyrim.alchemy.structure.EffectAlias", "es.skyrim.alchemy.structure.EffectReference", "es.skyrim.alchemy.structure.Ingredient", "es.skyrim.alchemy.structure.IngredientReference", "es.skyrim.alchemy.structure.Mixture", "es.skyrim.alchemy.structure.Recipe"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 1:
        return new Effect_BehaviorDescriptor();
      case 2:
        return new EffectAlias_BehaviorDescriptor();
      case 0:
        return new AlchemyLab_BehaviorDescriptor();
      case 4:
        return new Ingredient_BehaviorDescriptor();
      case 3:
        return new EffectReference_BehaviorDescriptor();
      case 6:
        return new Mixture_BehaviorDescriptor();
      case 5:
        return new IngredientReference_BehaviorDescriptor();
      case 7:
        return new Recipe_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
