package es.skyrim.alchemy.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EffectReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public EffectReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "es.skyrim.alchemy.structure.EffectReference";
  }
}
