package es.skyrim.alchemy.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class Effect_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IEffect_BehaviorDescriptor {
  public Effect_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "es.skyrim.alchemy.structure.Effect";
  }
}
