package es.skyrim.alchemy.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface IIngredient_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
}
