package es.skyrim.alchemy.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class IngredientReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public IngredientReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "es.skyrim.alchemy.structure.IngredientReference";
  }
}
