package es.skyrim.alchemy.behavior;

/*Generated by MPS */


public class Poison_BehaviorDescriptor extends Mixture_BehaviorDescriptor {
  public Poison_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "es.skyrim.alchemy.structure.Poison";
  }
}
