package es.skyrim.alchemy.behavior;

/*Generated by MPS */


public class Potion_BehaviorDescriptor extends Mixture_BehaviorDescriptor {
  public Potion_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "es.skyrim.alchemy.structure.Potion";
  }
}
