package es.skyrim.alchemy.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Recipe_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Recipe_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "es.skyrim.alchemy.structure.Recipe";
  }
}
