/*
 * generated by Xtext
 */
package es.skyrim.alchemy.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AlchemyLabExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return es.skyrim.alchemy.ui.internal.AlchemyLabActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return es.skyrim.alchemy.ui.internal.AlchemyLabActivator.getInstance().getInjector("es.skyrim.alchemy.AlchemyLab");
	}
	
}
