/*
 * generated by Xtext
 */
package es.skyrim.alchemy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlchemyLabRuntimeModule extends es.skyrim.alchemy.AbstractAlchemyLabRuntimeModule {

}
